services:

  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
    working_dir: /app
    container_name: express
    command: ["node", "index.js"]
      
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - REPO_USER =${REPO_USER}
      - REPO_PASS =${REPO_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: express --interval 60