services:
  express:
    image: sasho78/express-app:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    container_name: express
    command: ["node", "index.js"]


  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\strpo\Docker\material-applications\express-app\config.json:/config.json
    command: --interval 60
