services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    container_name: express
    command: ["node", "index.js"]

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - REPO_USER=sasho78
      - REPO_PASS=dckr_pat_mHmxT7bRQMVurwndVXeZF3EWSuc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --scope express --interval 60
