name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  publish-docker-hub:
        name: Publish image to Docker Hub
        runs-on: ubuntu-latest
        steps:
        # Checkout to the repository
        - uses: actions/checkout@v2
    
        # We need to login so we can later push the image without issues.
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
              push: true
              tags: sasho78/express-app:latest